//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OfdbWgDataModel.Status {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ofdbgw {
        
        private ofdbgwStatus statusField;
        
        /// <remarks/>
        public ofdbgwStatus status {
            get {
                return this.statusField;
            }
            set {
                this.statusField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ofdbgwStatus {
        
        private string rcodeField;
        
        private string rcodedescField;
        
        private string modulField;
        
        private string ofdbgwversionField;
        
        private string ofdbgwdateField;
        
        private string verarbeitungszeitField;
        
        /// <remarks/>
        public string rcode {
            get {
                return this.rcodeField;
            }
            set {
                this.rcodeField = value;
            }
        }
        
        /// <remarks/>
        public string rcodedesc {
            get {
                return this.rcodedescField;
            }
            set {
                this.rcodedescField = value;
            }
        }
        
        /// <remarks/>
        public string modul {
            get {
                return this.modulField;
            }
            set {
                this.modulField = value;
            }
        }
        
        /// <remarks/>
        public string ofdbgwversion {
            get {
                return this.ofdbgwversionField;
            }
            set {
                this.ofdbgwversionField = value;
            }
        }
        
        /// <remarks/>
        public string ofdbgwdate {
            get {
                return this.ofdbgwdateField;
            }
            set {
                this.ofdbgwdateField = value;
            }
        }
        
        /// <remarks/>
        public string verarbeitungszeit {
            get {
                return this.verarbeitungszeitField;
            }
            set {
                this.verarbeitungszeitField = value;
            }
        }
    }
}
