//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OfdbWgDataModel.Ean {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ofdbgw {
        
        private ofdbgwResultat resultatField;
        
        /// <remarks/>
        public ofdbgwResultat resultat {
            get {
                return this.resultatField;
            }
            set {
                this.resultatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ofdbgwResultat {
        
        private ofdbgwResultatEintrag eintragField;
        
        /// <remarks/>
        public ofdbgwResultatEintrag eintrag {
            get {
                return this.eintragField;
            }
            set {
                this.eintragField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ofdbgwResultatEintrag {
        
        private string filmidField;
        
        private string fassungidField;
        
        private string titelField;
        
        private string titel_origField;
        
        private string jahrField;
        
        /// <remarks/>
        public string filmid {
            get {
                return this.filmidField;
            }
            set {
                this.filmidField = value;
            }
        }
        
        /// <remarks/>
        public string fassungid {
            get {
                return this.fassungidField;
            }
            set {
                this.fassungidField = value;
            }
        }
        
        /// <remarks/>
        public string titel {
            get {
                return this.titelField;
            }
            set {
                this.titelField = value;
            }
        }
        
        /// <remarks/>
        public string titel_orig {
            get {
                return this.titel_origField;
            }
            set {
                this.titel_origField = value;
            }
        }
        
        /// <remarks/>
        public string jahr {
            get {
                return this.jahrField;
            }
            set {
                this.jahrField = value;
            }
        }
    }
}
