//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.18444
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// This source code was auto-generated by xsd, Version=4.0.30319.17929.
// 
namespace OfdbWgDataModel.Search {
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    [System.Xml.Serialization.XmlRootAttribute(Namespace="", IsNullable=false)]
    public partial class ofdbgw {
        
        private ofdbgwEintrag[] resultatField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlArrayItemAttribute("eintrag", IsNullable=false)]
        public ofdbgwEintrag[] resultat {
            get {
                return this.resultatField;
            }
            set {
                this.resultatField = value;
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("xsd", "4.0.30319.17929")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(AnonymousType=true)]
    public partial class ofdbgwEintrag {
        
        private string idField;
        
        private string titelField;
        
        private string titel_origField;
        
        private string bildField;
        
        private string jahrField;
        
        /// <remarks/>
        public string id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
            }
        }
        
        /// <remarks/>
        public string titel {
            get {
                return this.titelField;
            }
            set {
                this.titelField = value;
            }
        }
        
        /// <remarks/>
        public string titel_orig {
            get {
                return this.titel_origField;
            }
            set {
                this.titel_origField = value;
            }
        }
        
        /// <remarks/>
        public string bild {
            get {
                return this.bildField;
            }
            set {
                this.bildField = value;
            }
        }
        
        /// <remarks/>
        public string jahr {
            get {
                return this.jahrField;
            }
            set {
                this.jahrField = value;
            }
        }
    }
}
